### ISSUE TITLE
3. Build login flow

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-url-management-service#3]
- [x] If no login cookie/localstorage value redirect to `https://s3o.ft.com/v2/authenticate?post=false&host=url-management.ft.com&redirect=http%3A%2F%2Furl-management.ft.com`.  (Might be nice to match the cookie rules that s3o-middleware uses).
- [x] On return from s3o pick that value out of the URL and store in cookie/localstorage and rewrite the URL to hide it so that people can't copy+paste their token and put the biz at risk.
- [x] Show some kind of welcome message.
- [x] 🎉 

(In the future we ever get access denied type responses from the next-url-management-api we should wipe the cookie and trigger a reauthentication …… <-- might not mean much now but may mean something later)

**Comment by TheoLeanse** [comment]
- [ ] if we ever get access denied type responses from the next-url-management-api we should wipe the cookie and trigger a reauthentication
- [ ] add intermediate 'logging you in' state between logged in and logged out
